### ISSUE TITLE
installing in python 3

### ISSUE THREAD

**Issue by sweetcolor** [keleshev/version#5]
$ pip install version
Collecting version
  Downloading version-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-j08wq0vk/version/setup.py", line 4, in <module>
        from version import __version__
      File "/tmp/pip-build-j08wq0vk/version/version.py", line 2, in <module>
        from itertools import izip_longest
    ImportError: cannot import name 'izip_longest'

use zip_longest from python 3 and izip_longest from python 2

**Comment by olesang** [comment]
I got the same problem. I tried to modify the version.py as below and then run 'python3 setup.py install'.  Because izip_longest was changed to zip_longest in python3.

```
file version.py

try:
    # Python 3
    from itertools import zip_longest as izip_longest
except ImportError:
    # Python 2
    from itertools import izip_longest
```

**Comment by francbartoli** [comment]
@olesang it is fixed by [d4b32b62f3641cf907e8e44e1d421fdac88f3413](https://github.com/keleshev/version/commit/d4b32b62f3641cf907e8e44e1d421fdac88f3413)
